let token='',selected='';const $=id=>document.getElementById(id);
const labels={unused:'غير مستخدم',active:'فعال',expired:'منتهي',suspended:'موقوف',revoked:'ملغى'};
const events={create:'إصدار كود',activation:'أول تفعيل',binding:'ربط تثبيت',verification:'تحقق',extend:'تمديد',suspend:'إيقاف مؤقت',reactivate:'إعادة تفعيل',revoke:'إلغاء نهائي','reset-device':'إعادة ربط',transfer:'نقل',invalid_signature:'توقيع غير صالح'};
const fmt=d=>d?new Date(d).toLocaleString('ar',{dateStyle:'short',timeStyle:'short'}):'—';
const text=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
async function api(path,body){const res=await fetch(path,{method:body===undefined?'GET':'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)}),cache:'no-store'});const data=await res.json();if(!res.ok||data.error)throw Error(data.error||'تعذر إكمال الطلب');return data;}
async function run(fn){$('notice').textContent='';const buttons=[...document.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){$('notice').textContent=`تعذر إكمال العملية: ${e.message}`;}finally{buttons.forEach(b=>b.disabled=false);}}
async function load(){const items=await api('/admin/licenses?search='+encodeURIComponent($('search').value));$('licenses').replaceChildren();$('empty').hidden=items.length>0;for(const l of items){const tr=document.createElement('tr'),key=text('td',l.masked_key);key.append(text('small',l.bundle_id||'لم يرتبط بتطبيق'));tr.append(key);const status=text('span',labels[l.status]||l.status);status.className='status '+l.status;const cell=document.createElement('td');cell.append(status);tr.append(cell);for(const value of [fmt(l.activated_at),fmt(l.expires_at),l.expires_at?Math.max(0,Math.ceil((new Date(l.expires_at)-Date.now())/86400000))+' يوم':'لم تبدأ',l.device_count,fmt(l.last_seen),l.transfers_remaining])tr.append(text('td',value));const more=document.createElement('td'),button=text('button','التفاصيل');button.onclick=()=>run(()=>detail(l.id));more.append(button);tr.append(more);$('licenses').append(tr);}}
async function detail(id){selected=id;const l=await api('/admin/licenses/'+id);$('detailSummary').replaceChildren(text('div',`رقم الترخيص: ${l.id}`),text('div',`الحالة: ${labels[l.status]||l.status} | المراجعة: ${l.revision}`),text('div',`أول تفعيل: ${fmt(l.activated_at)} | الانتهاء: ${fmt(l.expires_at)}`),text('div',`التطبيق: ${l.bundle_id||'لم يُربط'} | مرات النقل المتبقية: ${l.transfers_remaining}`));$('installations').replaceChildren(...l.installations.map(i=>text('div',`${i.id} — ${i.bound?'مرتبط':'ارتباط سابق'} — آخر تحقق: ${fmt(i.last_seen)}`)));if(!l.installations.length)$('installations').append(text('div','لا يوجد تثبيت مرتبط.'));$('audit').replaceChildren(...l.audit.map(a=>{const tr=document.createElement('tr');[events[a.event]||a.event,a.actor,fmt(a.created_at)].forEach(v=>tr.append(text('td',v)));return tr;}));if(!$('detail').open)$('detail').showModal();}
$('loginForm').onsubmit=e=>{e.preventDefault();token=$('token').value;run(async()=>{await load();$('token').value='';$('login').hidden=true;$('workspace').hidden=false;$('logout').hidden=false;});};
$('logout').onclick=()=>{token='';selected='';$('workspace').hidden=true;$('login').hidden=false;$('logout').hidden=true;$('newKey').hidden=true;$('keyValue').value='';$('detail').close();$('licenses').replaceChildren();};
$('createForm').onsubmit=e=>{e.preventDefault();const form=new FormData(e.target);run(async()=>{const l=await api('/admin/licenses',{duration_days:Number(form.get('duration_days')),transfer_limit:Number(form.get('transfer_limit'))});$('keyValue').value=l.key;$('newKey').hidden=false;await load();});};
$('searchForm').onsubmit=e=>{e.preventDefault();run(load);};$('copyKey').onclick=()=>run(()=>navigator.clipboard.writeText($('keyValue').value));$('dismissKey').onclick=()=>{$('newKey').hidden=true;$('keyValue').value='';};$('closeDetail').onclick=()=>$('detail').close();
document.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>{const action=button.dataset.action;if(!selected)return;const warnings={revoke:'الإلغاء نهائي ولا يمكن التراجع عنه. هل تتابع؟','reset-device':'سيُلغى ارتباط التثبيت الحالي وتُستهلك مرة نقل. التثبيت الجديد يجب أن يكون لنفس التطبيق. هل تتابع؟',suspend:'هل توقف هذا الاشتراك مؤقتًا؟'};if(warnings[action]&&!confirm(warnings[action]))return;run(async()=>{await api(`/admin/licenses/${selected}/${action}`,action==='extend'?{days:Number($('extendDays').value)}:{});await detail(selected);await load();});});
